### ISSUE TITLE
Issues with evaluate the model on OOD test set

### ISSUE THREAD

**Issue by ShravanthiPatil** [hendrycks/anomaly-seg#13]
Hello,
I could train the PSPnet with a single GPU. However, I am having issues with the evaluation of the model on the out-of-distribution test set.
python3 eval_ood.py --cfg ./config/ade20k-resnet50dilated-ppm_deepsup.yaml --gpu 0 --ood msp

Here is the error:
Traceback (most recent call last):
  File "eval_ood.py", line 274, in <module>
    cfg.merge_from_list(ood)
  File "/home/spati12s/anaconda3/envs/anomaly-seg/lib/python3.6/site-packages/yacs/config.py", line 239, in merge_from_list
    subkey in d, "Non-existent key: {}".format(full_key)
  File "/home/spati12s/anaconda3/envs/anomaly-seg/lib/python3.6/site-packages/yacs/config.py", line 521, in _assert_with_logging
    assert cond, msg
AssertionError: Non-existent key: OOD.exclude_back
/var/spool/slurmd/job362065/slurm_script: line 21: /home/spati12s: Is a directory
~

**Comment by ShravanthiPatil** [comment]
Solved. 
Installing yacs either via conda or Pip does not help resolve the above-mentioned error. 
conda install -c conda-forge yacs
 or 
pip install yacs

Instead, use of git repo: https://github.com/rbgirshick/yacs, helps resolve the mentioned issue.
